# Site settings
title: Sketch Developers
email: developer@sketchapp.com
# url: "http://developer.sketchapp.com"

# Build settings
kramdown:
  input: GFM
  auto_ids: true
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    fenced_code_blocks: true
    default_lang: javascript
    span:
      disable: true
    block:
      line_numbers: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

sass:
  style: compressed
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - .sass-cache
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - DEVNOTES.md

# Dynamic Content
collections:
  actions:
    output: true
    permalink: /reference/action/:path/
  introduction:
    output: true
    permalink: /introduction/:path/
  posts:
    output: true
    permalink: /blog/:path/
  generated-plugins:
    output: true
    permalink: /examples/plugins/:path/

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "single-page"
  -
    scope:
      type: "actions"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "code-examples"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "introduction"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "generated-plugins"
    values:
      layout: "docco-page"
  -
    scope:
      path: "reference/api"
    values:
      layout: "api-page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
